### ISSUE TITLE
Correct answer not unescaped.

### ISSUE THREAD

**Issue by kaeza** [tryton-vanmeer/LibreTrivia#13]
The correct answer text is not unescaped, which gives it away.

Here's a nice example. Note how the raw HTML entity is shown only for the correct answer:

![screenshot](https://i.imgur.com/VF3Kben.png)

Edit: LibreTrivia 0.2.3 from F-Droid.

**Comment by kaeza** [comment]
Here's another example:

![a](https://i.imgur.com/DBRjcLX.png)

**Comment by mesunnyeveryday** [comment]
Yet, the problem still exists on the latest version

**Comment by mesunnyeveryday** [comment]
![Screenshot_20190628-222525_LibreTrivia](https://user-images.githubusercontent.com/52338544/60378755-7de97580-99f5-11e9-8cff-e4963cedfb0b.png)
![Screenshot_20190628-221145_LibreTrivia](https://user-images.githubusercontent.com/52338544/60378760-8cd02800-99f5-11e9-9b15-b06617769d78.png)
![Screenshot_20190628-221128_LibreTrivia](https://user-images.githubusercontent.com/52338544/60378761-93f73600-99f5-11e9-8f67-6d3074e0e782.png)

**Comment by mesunnyeveryday** [comment]
![Screenshot_20190628-222448_LibreTrivia](https://user-images.githubusercontent.com/52338544/60378766-c2751100-99f5-11e9-9403-85b00c401a94.png)
![Screenshot_20190628-222055_LibreTrivia](https://user-images.githubusercontent.com/52338544/60378768-c9038880-99f5-11e9-965d-ccb9ba58ae86.png)
![Screenshot_20190628-221913_LibreTrivia](https://user-images.githubusercontent.com/52338544/60378769-d0c32d00-99f5-11e9-8786-5c5e78d188fa.png)
![Screenshot_20190628-221618_LibreTrivia](https://user-images.githubusercontent.com/52338544/60378773-dae52b80-99f5-11e9-8bbb-7653c6bbc2f9.png)
![Screenshot_20190628-221056_LibreTrivia](https://user-images.githubusercontent.com/52338544/60378775-e0db0c80-99f5-11e9-8e0c-db02137ddb70.png)

**Comment by lgommans** [comment]
@mesunnyeveryday There has not been a new release since before the code was fixed.

**Comment by mesunnyeveryday** [comment]
That was May 14th 2018, 14 months ago.

Why hasn't it been updated ?

**Comment by lgommans** [comment]
@mesunnyeveryday I can't tell whether you're being indignant or just curious. You're also asking the wrong person: the repository owner doesn't get a notification of this thread as far as I can tell and they are the only ones that can create new releases.

@tryton-vanmeer Someone seems to be requesting a new release, would it be a lot of work to do one? I'm not sure what it involves to get it to f-droid etc.

**Comment by mesunnyeveryday** [comment]
Curious if it's really fixed.  It's a nice program.

I emailed him to see if he can upload a new version.
