### ISSUE TITLE
f-droid link to the app doesn't seem to be working

### ISSUE THREAD

**Issue by priteshusadadiya** [tryton-vanmeer/LibreTrivia#8]
404 Page Not Found error is getting displayed.

can you please check and correct the link if it's broken ?

current link : https://f-droid.org/app/io.github.trytonvanmeer.libretrivia/

**Comment by tryton-vanmeer** [comment]
Ya, app wasn't on their site yet when I added the badge. But had wrong link with /app/ instead of /packages/. Link is fixed now.

**Comment by licaon-kter** [comment]
@tryton-vanmeer Any reason to Tag as `vX.Y.Z` but version is `X.Y` since 0.3?
This breaks F-Droid Autoupdate as fdroid build bot will try to build from commit `vX.Y` instead

Ref: https://f-droid.org/wiki/page/io.github.trytonvanmeer.libretrivia/lastbuild_3
